library(fastbaps)
library(ggtree)
library(phytools)
library(ggplot2)

# Loading fasta file
u19.data <- import_fasta_sparse_nt("U19_uniq-TPA_Public_nic_SNP_only.fasta")

# Estimating the variance of the Dirichlet prior on the component mixtures
u19.data <- optimise_prior(u19.data, type = "optimise.symmetric")

# Running fastbaps
u19.baps.hc <- fast_baps(u19.data)
u19.best.partition <- best_baps_partition(u19.data, u19.baps.hc)

# Loading phylogeny tree generated by iqtree
u19.iqtree <- read.newick("U19_uniq-TPA_Public_nic_SNP_only.fasta.treefile")

# Plotting the results
u19.plot.df <- data.frame(id = colnames(u19.data$snp.matrix), 
                          fastbaps = u19.best.partition, 
                          stringsAsFactors = FALSE)
u19.gg <- ggtree(u19.iqtree)

facet_plot(u19.gg, panel = "fastbaps", data = u19.plot.df, geom = geom_tile,
           aes(x = fastbaps), color = "blue")
